services:
  frontend_dev:
    container_name: frontend_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3715:80"
    networks:
      - test-network
networks:
  test-network:
    external: true
