services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: Dev_Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - test-network
    depends_on:
      - database
  database:
    image: postgres:17.6-alpine
    container_name: incexp_database
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_MAP_PORT}:${POSTGRES_PORT}
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - test-network
networks:
  test-network:
    external: true
volumes:
  database_data:
