FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install 
COPY . .
RUN npm run build
RUN npm prune --omit=dev

FROM node:22-alpine AS prod
WORKDIR /app
COPY package*.json .
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
EXPOSE 6900
CMD ["npm", "run", "start:prod"]