name: IncomeExpenseApp
services:
  database:
    image: postgres:17.5-alpine
    container_name: incexp_database
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - the-network
networks:
  the-network:
volumes:
  database_data:
