/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'

const ProfileIndexLazyRouteImport = createFileRoute('/profile/')()
const CalendarEntryIndexLazyRouteImport = createFileRoute('/calendarEntry/')()
const CalendarEntryDateLazyRouteImport = createFileRoute(
  '/calendarEntry/$date',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexLazyRoute = ProfileIndexLazyRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const CalendarEntryIndexLazyRoute = CalendarEntryIndexLazyRouteImport.update({
  id: '/calendarEntry/',
  path: '/calendarEntry/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/calendarEntry/index.lazy').then((d) => d.Route),
)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))
const CalendarEntryDateLazyRoute = CalendarEntryDateLazyRouteImport.update({
  id: '/calendarEntry/$date',
  path: '/calendarEntry/$date',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/calendarEntry/$date.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendarEntry/$date': typeof CalendarEntryDateLazyRoute
  '/auth': typeof AuthIndexRoute
  '/calendarEntry': typeof CalendarEntryIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendarEntry/$date': typeof CalendarEntryDateLazyRoute
  '/auth': typeof AuthIndexRoute
  '/calendarEntry': typeof CalendarEntryIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendarEntry/$date': typeof CalendarEntryDateLazyRoute
  '/auth/': typeof AuthIndexRoute
  '/calendarEntry/': typeof CalendarEntryIndexLazyRoute
  '/profile/': typeof ProfileIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendarEntry/$date'
    | '/auth'
    | '/calendarEntry'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendarEntry/$date' | '/auth' | '/calendarEntry' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/calendarEntry/$date'
    | '/auth/'
    | '/calendarEntry/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarEntryDateLazyRoute: typeof CalendarEntryDateLazyRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CalendarEntryIndexLazyRoute: typeof CalendarEntryIndexLazyRoute
  ProfileIndexLazyRoute: typeof ProfileIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendarEntry/': {
      id: '/calendarEntry/'
      path: '/calendarEntry'
      fullPath: '/calendarEntry'
      preLoaderRoute: typeof CalendarEntryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendarEntry/$date': {
      id: '/calendarEntry/$date'
      path: '/calendarEntry/$date'
      fullPath: '/calendarEntry/$date'
      preLoaderRoute: typeof CalendarEntryDateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarEntryDateLazyRoute: CalendarEntryDateLazyRoute,
  AuthIndexRoute: AuthIndexRoute,
  CalendarEntryIndexLazyRoute: CalendarEntryIndexLazyRoute,
  ProfileIndexLazyRoute: ProfileIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
